apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: dev-cluster
  namespace: shared
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    nodePools:
    - name: default-nodepool
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
  settings:
    storage:
      defaultClass: vc01cl01-t0compute
    network:
      trust:
        additionalTrustedCAs:
        - name: mkcert
          data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZNRENDQTVpZ0F3SUJBZ0lSQVBCVUczVnlISUN2TFQ2cTJtR0xLVU13RFFZSktvWklodmNOQVFFTEJRQXcKZ2E4eEhqQWNCZ05WQkFvVEZXMXJZMlZ5ZENCa1pYWmxiRzl3YldWdWRDQkRRVEZDTUVBR0ExVUVDd3c1WkdSaApjbTlqYUdGQVF6QXlXRGt5TVZCS1IwZzFMblp0ZDJGeVpTNWpiMjBnS0VScFpXZHZJRkJsY21WcGNtRWdaR0VnClVtOWphR0VwTVVrd1J3WURWUVFEREVCdGEyTmxjblFnWkdSaGNtOWphR0ZBUXpBeVdEa3lNVkJLUjBnMUxuWnQKZDJGeVpTNWpiMjBnS0VScFpXZHZJRkJsY21WcGNtRWdaR0VnVW05amFHRXBNQjRYRFRJeU1EUXhNVEU0TVRZMApNRm9YRFRNeU1EUXhNVEU0TVRZME1Gb3dnYTh4SGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1CmRDQkRRVEZDTUVBR0ExVUVDd3c1WkdSaGNtOWphR0ZBUXpBeVdEa3lNVkJLUjBnMUxuWnRkMkZ5WlM1amIyMGcKS0VScFpXZHZJRkJsY21WcGNtRWdaR0VnVW05amFHRXBNVWt3UndZRFZRUURERUJ0YTJObGNuUWdaR1JoY205agphR0ZBUXpBeVdEa3lNVkJLUjBnMUxuWnRkMkZ5WlM1amIyMGdLRVJwWldkdklGQmxjbVZwY21FZ1pHRWdVbTlqCmFHRXBNSUlCb2pBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVk4QU1JSUJpZ0tDQVlFQTVmSnM1UzNoWEpjSmQ4TU4KTEdVTmdmTm5YRURTMkh6UWRFSTBMd1Z0QWhkMWMxT2VLZ1BsY1FYT3EzdDNLKythNFNDckx2WVhJSmRhOFdpbQpVQ0dBQWtiay9pV2dDcVVvS3E5SktUZ2VQNGVFU2wvV1VSbXdrVkk3d1pndHRTWjhEcUZ2ZGthMzByUEIxMHphCjhiOUtTRXRtZWl2WWxmMEsxMU9CNWNLOEJuZ1VjUEFHcXNuekkzdHRJWU5qTDdaMTRsRnFnYXF3SjZwS0lLS0YKYi9hcmRpODczNlE0cXNMMlhrS1U2d1JNMTBoRDVQTmtMWmZkSS9yUEcwakd3Nk9BdUJXNVVhZ1NHdUQxTUEzTQpzL05UWDZsRWQ5RkpZeUtnVUtzRW54WmM5TTZYNkdOb0cydDNBeHlBMHl5bm5IeWx4NythanlWWXVBK2dadDYwCnY2VFZRT2xoM29WbmNZZ0grQlhlb00xR2VYdURtTjdOZFZEYVUybzIwUDVvTHBRQ0R1cG1mODM2RFJNay9yWDMKNEhUcXN6elVTWFdtNnlhemR4RkZuWkFDeE93OEE4MlRVVnJ3MXdUbW1KRWZzSU1WcE1DSnNOSS9Naml0UTdSNwprd0dmT2xSMG95dnhBeUxsY1FXSWF2dGhqaXFPVGFMOTR6S1VwVy82cWlRcVFYZzNBZ01CQUFHalJUQkRNQTRHCkExVWREd0VCL3dRRUF3SUNCREFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJUWjRhTTAKVXcvV0lab3NiNHlPN1Jhdm1aU2NYREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBUnJXWkU5OUFvSnh1ZGpzSQpkMlE1d3VlSGZDUnJDT3JuSFFCcjUyWFI2UVRCMHhCdnQybXJQVWhNek81V0NvQmc4NWFtclk1SEdSZENPTlNtClZZMXQ3UGJZa1MrRDIzNmlKVlZBaDRTSXh5akNtR3YwY2RzdVJpYUc2QVpEUU5nR2pIWGJvUkIyMXl3MkR3V2EKRlQ2Z2VCNGJXamNnaVJlYk9XVHB4czVQejgyakZXRCt5TEFzTHBFbGEvQm9KWnQ5ZXBxaCtMTDF5ZjZVeXRxcQpLbmluSTF4OXdVTkhwZzVMZURhaTVqeGFGZmZaMldLdHg3WDd6SWxpb3dXWmVIRURybkVEdzZzcmR2MFA5bFdpCjdHSUVQVVR0amlYSyswMllCOUtTRkZIT0VtWGp6aGJLMjA5dm9NbE56WFRZUDlOMndJSldub3RkWjFCV3VUNEYKMG8wOEY1NXVDRWtnbTFUNC9LeHJZUllQZ3VCenJZbXJraVQyb2ZldHRLeXB0NXNNNzNYMzdGQTVPb2t4RVA1UQozRXUyMnV0QTBZcTk5T1BOU0ZWM3A0SS8vYWVFQm9QVjRxMWRzQlBqQnNEVVYwc3JIRHdDOVhickt2RHZiVGo1CnM5M3UxSTdBNCtBdVZtN0RDTUpEenVSbWE4ZXJjZkltcStzdWxjSGdRT1pIcC9YTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
